language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: bewildered-fall.surge.sh
  project: ./build/
on:
  branch: master

after_success:
- echo "vuong ftp upload"
- curl --ftp-create-dirs
       -T build/
       sftp://${FTP_USER}:${FTP_PASSWORD}@ftpupload.net/htdocs