language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: bewildered-fall.surge.sh
  project: ./build/
on:
  branch: master

# Upload site using FTP.
# -exec must be closed with ";" which must be escaped (hence the "s).
# Finds all files and calls curl to upload them for every file.
after_success:
    - curl --ftp-create-dirs --ftp-ssl -p -k  -T ./build/ --user $FTP_USER:$FTP_PASSWORD  ftp://ftpupload.net/htdocs